### ISSUE TITLE
Отсутствуют автоматические тесты

### ISSUE THREAD

**Issue by AlexeySorokin** [Naimdzhon/Practicum_1#2]
Сделайте возможность запускать перечисленные тесты двумя командами, например
```
g++ test.cpp -o test.out
./test.out
```
где `test.cpp` должен содержать логику тестирования.

**Comment by Naimdzhon** [comment]
Сделал отдельный файл test.cpp, при этом изменил Problem.cpp на Problem.h

**Comment by AlexeySorokin** [comment]
Вообще, конечно, правильно проверять, проходятся ли тесты, а не просто печатать ответы.
