### ISSUE TITLE
TL

### ISSUE THREAD

**Issue by AlexeySorokin** [Naimdzhon/Practicum_1#3]
Медленно работает на тестах со звёздочкой, попробуйте ускорить алгоритм.

**Comment by Naimdzhon** [comment]
Если честно, я порядка 3-х дней думал как ускорить алгоритм , но не смог придумать никаких идей.

**Comment by AlexeySorokin** [comment]
Попытаться не делать лишние умножения, когда они не влияют на результат.

**Comment by Naimdzhon** [comment]
Умножения я делаю только в двух местах : 
1) Для конкатенации двух выражений. Здесь обязательно нужно делать умножение, ибо результат может меняться.
2) Для Замыкания Клини. Здесь я сворачиваю выражение на k - конкатенирующих множителей, так как мы должны найти ответ для каждого остатка. Ну получается, что здесь тоже никак не получится упростить алгоритм.

**Comment by AlexeySorokin** [comment]
В общем случае всё верно, но для конкретного условия расчёты можно упростить.

**Comment by Naimdzhon** [comment]
В моём решении я не вижу частного случая, так как я вычисляю всё последовательно. Если в каком-нибудь шаге рассмотреть конкретные случаи, то в дальнейшем могут возникнуть ошибки, не именно с остатком l, а с другими остатками.

**Comment by AlexeySorokin** [comment]
Язык для звёздочки формально определяется как бесконечное объединение, но считается он, естественно, конечным образом. Это вычисление надо как можно сильнее упростить, чтобы в некоторых типичных случаях оно считалось очень быстро.

**Comment by Naimdzhon** [comment]
Немного ускорил код, использовав быстрое возведение в степень.
