### ISSUE TITLE
Нет основного файла

### ISSUE THREAD

**Issue by AlexeySorokin** [Naimdzhon/Practicum_1#4]
Как теперь запускать программу на выполнение, а не на тестирование?

**Comment by Naimdzhon** [comment]
Просто нужно собрать пустой проект и добавить эти два файлы в проект.

**Comment by AlexeySorokin** [comment]
Вопрос был в другом: запуск на тестирование и на выполнение должны быть в разных файлах и в идеале в разных сборках. Закрою это замечание только из-за позднего времени.
